package dev.mariinkys.kantan.util

private val TAG_DESCRIPTIONS: Map<String, String> = mapOf(
    // Parts of speech
    "adj-f" to "Prenominal",
    "adj-i" to "I-adjective",
    "adj-ix" to "I-adjective (yoi/ii)",
    "adj-kari" to "Kari-adjective (archaic)",
    "adj-ku" to "Ku-adjective (archaic)",
    "adj-na" to "Na-adjective",
    "adj-nari" to "Nari-adjective (archaic)",
    "adj-no" to "No-adjective",
    "adj-pn" to "Pre-noun adjective",
    "adj-shiku" to "Shiku-adjective (archaic)",
    "adj-t" to "Taru-adjective",
    "adv" to "Adverb",
    "adv-to" to "Adverb (to)",
    "aux" to "Auxiliary",
    "aux-adj" to "Auxiliary adjective",
    "aux-v" to "Auxiliary verb",
    "conj" to "Conjunction",
    "cop" to "Copula",
    "ctr" to "Counter",
    "exp" to "Expression",
    "int" to "Interjection",
    "n" to "Noun",
    "1" to "Noun",
    "n-adv" to "Adverbial noun",
    "n-pr" to "Proper noun",
    "n-pref" to "Noun prefix",
    "n-suf" to "Noun suffix",
    "n-t" to "Temporal noun",
    "num" to "Numeric",
    "pn" to "Pronoun",
    "pref" to "Prefix",
    "prt" to "Particle",
    "suf" to "Suffix",
    "unc" to "Unclassified",
    "v1" to "Ichidan verb",
    "v1-s" to "Ichidan verb (kureru)",
    "v5aru" to "Godan verb (-aru)",
    "v5b" to "Godan verb (ぶ)",
    "v5g" to "Godan verb (ぐ)",
    "v5k" to "Godan verb (く)",
    "v5k-s" to "Godan verb (iku/yuku)",
    "v5m" to "Godan verb (む)",
    "v5n" to "Godan verb (ぬ)",
    "v5r" to "Godan verb (る)",
    "v5r-i" to "Godan verb (る, irregular)",
    "v5s" to "Godan verb (す)",
    "v5t" to "Godan verb (つ)",
    "v5u" to "Godan verb (う)",
    "v5u-s" to "Godan verb (う, special)",
    "v5uru" to "Godan verb (uru)",
    "vi" to "Intransitive",
    "vk" to "Kuru verb",
    "vn" to "Irregular nu verb",
    "vr" to "Irregular ru verb",
    "vs" to "Suru verb",
    "vs-c" to "Su verb (precursor)",
    "vs-i" to "Suru verb (included)",
    "vs-s" to "Suru verb (special)",
    "vt" to "Transitive",
    "vz" to "Ichidan verb (-zuru)",
    // Miscellaneous
    "abbr" to "Abbreviation",
    "arch" to "Archaic",
    "chn" to "Children's language",
    "col" to "Colloquial",
    "dated" to "Dated",
    "derog" to "Derogatory",
    "euph" to "Euphemistic",
    "fam" to "Familiar",
    "fem" to "Female term",
    "form" to "Formal",
    "hist" to "Historical",
    "hon" to "Honorific",
    "hum" to "Humble",
    "id" to "Idiomatic",
    "joc" to "Humorous",
    "m-sl" to "Manga slang",
    "male" to "Male term",
    "net-sl" to "Internet slang",
    "obs" to "Obsolete",
    "on-mim" to "Onomatopoeia",
    "poet" to "Poetical",
    "pol" to "Polite",
    "proverb" to "Proverb",
    "rare" to "Rare",
    "sens" to "Sensitive",
    "sl" to "Slang",
    "uk" to "Usually kana",
    "vulg" to "Vulgar",
    "yoji" to "Yojijukugo",
    "X" to "Adult content",
    // Frequency
    "ichi" to "Common (Ichimango)",
    "spec" to "Common (JMdict)",
    "gai" to "Common loanword",
    "⭐" to "Common word",
    // Reading / kanji info
    "gikun" to "Gikun reading",
    "ik" to "Irregular kana",
    "ok" to "Outdated kana",
    "rk" to "Rare kana",
    "ateji" to "Ateji reading",
    "iK" to "Irregular kanji",
    "io" to "Irregular okurigana",
    "oK" to "Outdated kanji",
    "rK" to "Rare kanji",
)

/** Resolves a raw tag code to a display label. */
fun resolveTag(raw: String): String {
    TAG_DESCRIPTIONS[raw]?.let { return it }
    // news1k … news24k  →  "Top 1k words", "Top 2k words", …
    val newsMatch = Regex("""^news(\d+)k$""").find(raw)
    if (newsMatch != null) return "Top ${newsMatch.groupValues[1]}k words"
    return raw // fall back to the raw code if unknown
}