name: Android Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name (e.g: 1.0.0)'
        required: true
        type: string
      release_name:
        description: 'Release name (e.g: Release 1.0.0)'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Extract Kanji Assets
        run: |
          mkdir -p app/src/main/assets/
          unzip app/src/main/assets/kanji.zip -d app/src/main/assets

      - name: Set up JDK 25
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'gradle'

      - name: Build Both Variants Release APK
        run: ./gradlew assembleFullRelease assembleFossRelease

      - name: Debug APK output
        run: find app/build/outputs/apk -type f

      - name: Sign and Align APK
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          # 1. Find build tools
          BUILD_TOOLS_PATH=$(ls -d $ANDROID_HOME/build-tools/* | tail -1)
          
          # 2. Decode keystore from the env variable
          echo "$SIGNING_KEY" | base64 -d > release.jks
          
          # 3.1 Align the Full Variant APK
          $BUILD_TOOLS_PATH/zipalign -v 4 app/build/outputs/apk/full/release/app-full-release-unsigned.apk full-aligned.apk
          
          # 4.1 Sign the Full APK 
          $BUILD_TOOLS_PATH/apksigner sign --ks release.jks \
            --ks-key-alias "$ALIAS" \
            --ks-pass pass:"$KEY_PASSWORD" \
            --key-pass pass:"$KEY_PASSWORD" \
            --out kantan-full-${{ github.event.inputs.tag_name }}.apk \
            full-aligned.apk
          
          # 3.2 Align the Foss Variant APK
          $BUILD_TOOLS_PATH/zipalign -v 4 app/build/outputs/apk/foss/release/app-foss-release-unsigned.apk foss-aligned.apk
          
          # 4.2 Sign the Foss APK 
          $BUILD_TOOLS_PATH/apksigner sign --ks release.jks \
            --ks-key-alias "$ALIAS" \
            --ks-pass pass:"$KEY_PASSWORD" \
            --key-pass pass:"$KEY_PASSWORD" \
            --out kantan-foss-${{ github.event.inputs.tag_name }}.apk \
            foss-aligned.apk
          
          # 5. Cleanup
          rm release.jks full-aligned.apk foss-aligned.apk

      - name: Verify APKs exist
        run: |
          test -f kantan-full-${{ github.event.inputs.tag_name }}.apk
          test -f kantan-foss-${{ github.event.inputs.tag_name }}.apk

      - name: Generate APK Hashes
        id: generate_hash
        run: |
          full_sha=$(sha256sum kantan-full-${{ github.event.inputs.tag_name }}.apk | awk '{print $1}')
          foss_sha=$(sha256sum kantan-foss-${{ github.event.inputs.tag_name }}.apk | awk '{print $1}')

          echo "full_sha=$full_sha" >> $GITHUB_OUTPUT
          echo "foss_sha=$foss_sha" >> $GITHUB_OUTPUT

          echo "FULL SHA-256: $full_sha"
          echo "FOSS SHA-256: $foss_sha"

      - name: Create Draft Release with APKs
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          name: ${{ github.event.inputs.release_name }}
          draft: true
          files: |
            kantan-full-${{ github.event.inputs.tag_name }}.apk
            kantan-foss-${{ github.event.inputs.tag_name }}.apk
          body: |
            <!-- Write changelog here -->

            ---
            ### Security Verification
            **APK (Full) SHA-256 Hash:** `${{ steps.generate_hash.outputs.full_sha }}`
            **APK (Foss) SHA-256 Hash:** `${{ steps.generate_hash.outputs.foss_sha }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}